# Generated by Django 3.0.5 on 2020-04-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_electronics_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
