# Generated by Django 3.0.5 on 2020-04-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_electronics_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='name',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='value',
        ),
        migrations.AddField(
            model_name='electronics',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronics',
            name='specs',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronics',
            name='title',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
