# Generated by Django 3.0.5 on 2020-04-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200430_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='number',
            field=models.CharField(max_length=2),
        ),
    ]
